### ISSUE TITLE
Instalación + puesta en marcha

### ISSUE THREAD

**Issue by rafamerino** [covagashi/aemet_telegram_bot#3]
Buenas,

He hecho un pip3 install --user -r requirements.txt sin tener claro si es el comando adecuado, y entiendo la parte de la configuración (tengo token de bot + api de aemet), pero no tengo claro si estoy haciendo todos los pasos correctamente.

¿Sería posible añadir un breve resumen de instalación + ejecución del bot?

Gracias

**Comment by covagashi** [comment]
Esta app está hecha para heroku, en un momento te creo una miniguia

**Comment by covagashi** [comment]
He actualizado Readme, ahora espero que sea mas claro. @rafamerino

**Comment by rafamerino** [comment]
Gracias! Nunca trabajé con Heroku y pensé que se podía usar en consola normal directa. Saludos.
